BebeABa/Front/Controllers/ChildrenController.cs
using Front.ViewModels.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Shared;
using Shared.ApiUtilities;
using Shared.FilterModels;
using Shared.Helpers;
using Shared.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Front.Controllers
{
    public class ChildrenController : Controller
    {
        private readonly IChildrenViewModel _childrenViewModel;
        private readonly IConfiguration _configuration;
        private readonly IChildrenTimeLineViewModel _childrenTimeLineViewModel;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public ChildrenController(
            IChildrenViewModel childrenViewModel,
            IConfiguration configuration,
            IChildrenTimeLineViewModel childrenTimeLineViewModel,
            IHttpContextAccessor httpContextAccessor)
        {
            _childrenViewModel = childrenViewModel;
            _configuration = configuration;
            _childrenTimeLineViewModel = childrenTimeLineViewModel;
            _httpContextAccessor = httpContextAccessor;
        }
        [HttpGet]
        [Route("Children/Index/{childrenId:long}")]
        public IActionResult Index(long childrenId)
        {
            return View(childrenId);
        }

        public IActionResult RegisterChild()
        {
            return View();
        }

        public async Task<IActionResult> ChildrenProfile()
        {
            UserModel user = null;
            List<ChildrenModel> childrens = new List<ChildrenModel>(0);
            var cookieValue = _httpContextAccessor.HttpContext?.Request.Cookies["userLoggedBebeABa"];
            if (cookieValue != null)
            { user = JsonConvert.DeserializeObject<UserModel>(FunctionsHelper.Decrypt(cookieValue)); }
            if (user != null)
            {
                var response = await _childrenViewModel.GetChildrenByUserId(user.UserId);
                childrens = JsonConvert.DeserializeObject<List<ChildrenModel>>(response.Result.ToString());
            }

            return View(childrens);
        }

        public async Task<IActionResult> Save(IFormCollection formCollection)
        {
            var isOk = false;
            string msg = string.Empty;
            Response response = new Response();
            try
            {
                var files = formCollection.Files;
                var children = JsonConvert.DeserializeObject<ChildrenModel>(formCollection["ChildrenJson"]);
                if (children != null)
                {
                    if (files.Any() && files[0] is { Length: > 0 })
                    {
                        var extension = files[0].FileName.Split('.').Last();
                        if (extension == "jpeg" || extension == "jpg" || extension == "png")
                        {

                            var fileName = FunctionsHelper.GenerateNumbersRandom(0, 999999) + files[0].FileName;
                            var path = $"{Constants.ChildImagesPath}/{fileName}";

                            using (var fs = System.IO.File.Create(path))
                            { await files[0].CopyToAsync(fs); }
                            children.ImgPath = fileName;
                        }
                        else
                        {
                            msg = "Invalid format for the image";
                        }
                    }
                    response = await _childrenViewModel.CreateChildren(children);
                    if (response.Status == Shared.Enums.StatusCode.Success)
                    {
                        isOk = true;
                    }
                }
            }
            catch (Exception ex)
            {
            }


            return Json(new { success = isOk, message = msg });
        }

        public async Task<IActionResult> GridTimeLine(long childrenId)
        {
            string draw = string.Empty;
            int recordsTotal = 0;
            var data = new List<ChildrenTimeLineModel>(0);

            try
            {
                draw = Request.Form["draw"].FirstOrDefault();
                // Skip number of Rows count  
                var start = Request.Form["start"].FirstOrDefault();
                // Paging Length 10,20  
                var length = Request.Form["length"].FirstOrDefault();
                // Search Value from (Search box)  
                var searchValue = Request.Form["search[value]"].FirstOrDefault();

                var filters = new ChildrenTimeLineFilterModel
                {
                    Page = ((start != null ? Convert.ToInt32(start) : 0) / (length != null ? Convert.ToInt32(length) : 10)) + 1,
                    PageSize = length != null ? Convert.ToInt32(length) : 10,
                    ChildrenId = childrenId
                };
                if (childrenId > 0)
                {
                    var response = await _childrenTimeLineViewModel.GetChildrenTimeLineByFilters(filters);
                    if (response is not null && response.Status == Shared.Enums.StatusCode.Success)
                    {
                        var result = JsonConvert.DeserializeObject<FilterResultModel<ChildrenTimeLineModel>>(response.Result.ToString());
                        recordsTotal = result.Pager.TotalItems;
                        data = result.List;
                    }
                }

            }
            catch (Exception ex)
            { }

            return Json(new
            {
                draw = draw,
                recordsFiltered = recordsTotal,
                recordsTotal = recordsTotal,
                data = data
            });
        }


        public async Task<IActionResult> SaveTimeLine(IFormCollection formCollection)
        {
            var isOk = false;
            string msg = string.Empty;
            Response response = new Response();
            try
            {
                var files = formCollection.Files;
                var childrenTimeLine = JsonConvert.DeserializeObject<ChildrenTimeLineModel>(formCollection["ChildrenTimeLineJson"]);
                if (childrenTimeLine != null)
                {

                    var childResponse = await _childrenViewModel.GetChildrenById(childrenTimeLine.ChildrenId);
                    var child = JsonConvert.DeserializeObject<ChildrenModel>(childResponse.Result.ToString());
                    if (child != null)
                    {
                        int childAge = childrenTimeLine.TimeLineDate.Year - child.BirthDate.Year;
                        childrenTimeLine.ChildAge = childAge;
                    }

                    if (files.Any() && files[0] is { Length: > 0 })
                    {

                        var inputFileName = files[0].FileName;
                        string fileName = $"{FunctionsHelper.GenerateNumbersRandom(0, 999999)}{inputFileName}";
                        var path = $"{Constants.ChildrenTimeLineImagesPath}/{fileName}";

                        using (var fs = System.IO.File.Create(path))
                        { await files[0].CopyToAsync(fs); }
                        childrenTimeLine.FilePath = fileName;
                    }
                    response = await _childrenTimeLineViewModel.Save(childrenTimeLine);
                    if (response.Status == Shared.Enums.StatusCode.Success)
                    {
                        isOk = true;
                    }
                }

            }
            catch (Exception ex)
            {
            }


            return Json(new { success = isOk, message = msg });
        }

        public IActionResult DownloadFile(string fileName)
        {
            var filePath = Path.Combine(Constants.ChildrenTimeLineImagesPath, fileName);

            if (System.IO.File.Exists(filePath))
            {
                var fileContent = System.IO.File.ReadAllBytes(filePath);

                var contentType = "application/octet-stream";

                return File(fileContent, contentType, fileName);
            }
            return NotFound();
        }
    }
}

BebeABa/Front/Controllers/ForumController.cs
using Front.ViewModels.Interface;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Shared.ApiUtilities;
using Shared.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Front.Controllers
{
    public class ForumController : Controller
    {
        private readonly IMainForumViewModel _mainForumViewModel;
        private readonly IForumAnswerViewModel _forumAnswerViewModel;

        public ForumController(IMainForumViewModel mainForumViewModel, IForumAnswerViewModel forumAnswerViewModel)
        {
            _mainForumViewModel = mainForumViewModel;
            _forumAnswerViewModel = forumAnswerViewModel;
        }
        public async Task<IActionResult> Index()
        {
            var response = await _mainForumViewModel.GetAllForum();

            var forum = JsonConvert.DeserializeObject<List<MainForumModel>>(response.Result.ToString());
            return View(forum);
        }

        public async Task<IActionResult> CreatePost(MainForumModel mainForum)
        {
            var isOk = false;
            string msg = string.Empty;
            Response response;
            MainForumModel model = new MainForumModel();

            try
            {

                if (mainForum != null)
                {
                    response = await _mainForumViewModel.CreateForum(mainForum);
                    model = JsonConvert.DeserializeObject<MainForumModel>(response.Result.ToString());
                    if (response.Status == Shared.Enums.StatusCode.Success)
                    {
                        isOk = true;
                    }
                }
            }
            catch (Exception ex)
            { }

            return Json(new {data = model, success = isOk, message = msg });
        }
        public async Task<IActionResult> CreateAnswer(ForumAnswerModel forumAnswer)
        {
            var isOk = false;
            string msg = string.Empty;
            Response response;
            ForumAnswerModel model = new ForumAnswerModel();

            try
            {

                if (forumAnswer != null)
                {
                    response = await _forumAnswerViewModel.CreateAnswer(forumAnswer);
                    model = JsonConvert.DeserializeObject<ForumAnswerModel>(response.Result.ToString());
                    if (response.Status == Shared.Enums.StatusCode.Success)
                    {
                        isOk = true;
                    }
                }
            }
            catch (Exception ex)
            { }

            return Json(new { data = model, success = isOk, message = msg });
        }
        public async Task<IActionResult> DeleteMainForum(long id)
        {
            Response response = null;

            if (id > 0)
            {
                response = await _mainForumViewModel.DeleteMainForum(id);
            }
            return Json(new { success = response is not null && response.Status == Shared.Enums.StatusCode.Success });
        }
        public async Task<IActionResult> DeleteAnswer(long id)
        {
            Response response = null;

            if (id > 0)
            {
                response = await _forumAnswerViewModel.DeleteAnswer(id);
            }
            return Json(new { success = response is not null && response.Status == Shared.Enums.StatusCode.Success });
        }
    }
}

BebeABa/Front/Views/Shared/_Layout.cshtml
@{
    var userLogged = JsonConvert.DeserializeObject<UserModel>(FunctionsHelper.Decrypt(Context.Request.Cookies["userLoggedBebeABa"]));
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="~/plugins/jquery-toast/jquery.toast.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">
    <link href="~/css/personalized.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" crossorigin="anonymous" />
</head>
<main>
    <div class="hamburger-menu">
        <input id="menu__toggle" type="checkbox" />
        <label class="menu__btn" for="menu__toggle">
            <span></span>
        </label>
        <ul class="menu__box">
            @if (!userLogged.IsDoctor)
            {
                <li><a class="menu__item" asp-controller="Children" asp-action="ChildrenProfile">Perfil</a></li>
                <li><a class="menu__item" asp-controller="Children" asp-action="RegisterChild">Cadastrar Filho</a></li>
            }
            <li><a class="menu__item" asp-controller="Forum" asp-action="Index">Fórum</a></li>
            <li><a class="menu__item" href="@Url.Action("Logout", "Logout")">Sair</a></li>
        </ul>
        <header style="text-align: center;">
            <strong>Bebê-a-Bá</strong>
            <nav>
                <strong>O DIA A DIA DO SEU AMOR</strong>
            </nav>
            <img src="~/img/baby1.svg" alt="" width="120" style="margin-top: 20px;">
        </header>
    </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>


 @*    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Front - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@

   

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="~/plugins/jquery-toast/jquery.toast.js"></script>
    <script src="~/js/bootstrap-waitingfor.js"></script>
    <script src="~/plugins/moment/moment.js"></script>
    <script src="~/app/app.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</main>

BebeABa/Front/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/personalized.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/app/app.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>